# Generated by Django 5.2.12 on 2026-03-14 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0041_alter_pageurl_unique_together_pageurl_site_and_more"),
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroPluginModel",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.TextField(blank=True)),
                ("image", models.FileField(blank=True, upload_to="hero/")),
                (
                    "cta_label",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="CTA label"
                    ),
                ),
                ("cta_url", models.URLField(blank=True, verbose_name="CTA URL")),
                ("is_highlighted", models.BooleanField(default=False)),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("centered", "Centered"),
                            ("left", "Left-aligned"),
                            ("right", "Right-aligned"),
                        ],
                        default="centered",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "categories",
                    models.ManyToManyField(blank=True, to="testapp.category"),
                ),
            ],
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="HeroButton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                ("url", models.URLField()),
                ("is_primary", models.BooleanField(default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "hero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buttons",
                        to="testapp.heropluginmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
    ]
